<project name="workoutApp" default="run-jar">

    <!-- JUnit Platform Console -->
    <property name="junitjar" location="lib/junit-platform-console-standalone-6.1.0-M1.jar"/>

    <!-- directories -->
    <property name="src.dir"     value="src"/>
    <property name="build.dir"   value="build"/>
    <property name="classes.dir" value="${build.dir}/classes"/>
    <property name="lib.dir"     value="lib"/>
    <property name="test.src.dir"     value="src"/>
    <property name="test.classes.dir"     value="${build.dir}/classes"/>

    <condition property="javafx.lib"     value="${lib.dir}/javafx-sdk-21.0.11-win/lib">
        <os family="windows"/>
    </condition>

    <condition property="javafx.lib"     value="${lib.dir}/javafx-sdk-21.0.11/lib">
        <os family="unix"/>
    </condition>

    <!-- classpath for compilation and tests -->
    <path id="compile.classpath">
        <fileset dir="${lib.dir}" includes="**/*.jar"/>
        <pathelement path="${classes.dir}"/>
    </path>

    <!-- clean -->
    <target name="clean">
        <delete dir="${build.dir}"/>
    </target>

    <!-- compile main sources -->
    <target name="compile" depends="clean">
        <mkdir dir="${classes.dir}"/>
        <copy todir="${classes.dir}">
            <fileset dir="src" includes="**/*.fxml"/>
            <fileset dir="src" includes="**/*.css"/>
        </copy>
        <javac srcdir="${src.dir}"
               destdir="${classes.dir}"
               includeantruntime="false"
               classpathref="compile.classpath"
               release="17" target="17">
    
            <!-- JavaFX module path -->
            <compilerarg value="--module-path"/>
            <compilerarg value="${javafx.lib}"/>
            <compilerarg value="--add-modules"/>
            <compilerarg value="javafx.controls,javafx.fxml"/>  
        </javac>  
    </target>

    <!-- compile test sources -->
    <target name="compile-tests" depends="compile">
        <mkdir dir="${test.classes.dir}"/>
        <javac srcdir="${test.src.dir}"
               destdir="${test.classes.dir}"
               includeantruntime="false"
               classpathref="compile.classpath"
               release="17" target="17"/>
    </target>

    <!-- run junit tests -->
    <target name="test" depends="compile-tests">
        <pathconvert property="test.classpath" pathsep="${path.separator}">
            <path>
                <pathelement path="${classes.dir}"/>
                <fileset dir="${lib.dir}" includes="**/*.jar"/>
            </path>
        </pathconvert>

        <java jar="${junitjar}" fork="true" failonerror="true">
            <arg value="execute"/>
            <arg value="--class-path"/>
            <arg value="${test.classpath}"/>

            <!-- Discover tests -->
            <arg value="--scan-class-path"/>

            <!-- Pretty output -->
            <arg value="--details"/>
            <arg value="tree"/>
            <arg value="--details-theme"/>
            <arg value="ascii"/>

            <!-- Include test classes -->
            <arg value="--include-classname"/>
            <arg value=".*Test"/>
        </java>
    </target>

    <!-- build and run application-->
    <target name="run-build" depends="compile">
        <java classname="com.workoutapp.app.Main" fork="true">
            <classpath>
                <pathelement path="${classes.dir}"/>
                <fileset dir="${lib.dir}" includes="**/*.jar"/>
            </classpath>

            <!-- JavaFX runtime module path -->
            <jvmarg value="--module-path"/>
            <jvmarg value="${javafx.lib}"/>
            <jvmarg value="--add-modules"/>
            <jvmarg value="javafx.controls,javafx.fxml,javafx.swing"/>
        </java>
    </target>

    <pathconvert property="manifest.classpath" pathsep=" ">
        <mapper type="glob" from="*.jar" to="../lib/*.jar"/>
        <path>
            <fileset dir="${lib.dir}" includes="**/*.jar"/>
        </path>
    </pathconvert>
    
    <!-- Build fat JAR with Gson merged, JavaFX external -->
    <target name="jar" depends="compile">
        <!-- Clean jar directory -->
        <delete file="WorkoutApp.jar"/>

        <!-- Create JAR -->
        <jar destfile="WorkoutApp.jar" basedir="${classes.dir}">
            
            <!-- Merge Gson into JAR -->
            <zipgroupfileset dir="${lib.dir}" includes="gson-*.jar"/>

            <!-- Include FXML + CSS -->
            <fileset dir="src" includes="**/*.fxml"/>
            <fileset dir="src" includes="**/*.css"/>

            <!-- Exclude tests -->
            <exclude name="**/*Test.class"/>
            <exclude name="**/com/workoutapptests/**"/>

            <!-- Manifest -->
            <manifest>
                <attribute name="Main-Class" value="com.workoutapp.app.Main"/>
                <attribute name="Class-Path"
                    value="../lib/javafx-base.jar ../lib/javafx-controls.jar ../lib/javafx-fxml.jar ../lib/javafx-graphics.jar"/>
            </manifest>
        </jar>
    </target>

    <!-- Run application from JAR (NOTE: Do "ant jar" first)-->
    <target name="run-jar">
        <java jar="WorkoutApp.jar" fork="true">
            <jvmarg value="--module-path"/>
            <jvmarg value="${javafx.lib}"/>
            <jvmarg value="--add-modules"/>
            <jvmarg value="javafx.controls,javafx.fxml,javafx.swing"/>
        </java>
    </target>

</project>
